# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: test@test.com
author_name: nb_sync
has_binder: true
has_settings: true
kind: frontend-and-server
labextension_name: nb_sync
project_short_description: A JupyterLab extension for teaching
python_name: nb_sync
repository: https://github.com/RETR0-OS/nb_sync_test
test: false

